### ISSUE TITLE
Is it possible to build on it for use in Ghana

### ISSUE THREAD

**Issue by OliverMensahDev** [Parbhat/echildcare#1]
I started with python this week and I am loving it. Is it possible to work this afterwards?

**Comment by Parbhat** [comment]
@OMENSAH Welcome to Python community.

Yes, you can use this project in Ghana. For that, you need to get familiar with [Django](https://www.djangoproject.com/) (Python Web framework) and [RapidSMS](https://www.rapidsms.org/) (Framework for building mobile services built with Python and Django). After learning these, you can add more features to echildcare and deploy it.
